server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/clientdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
