services:
  demo-application:
    build:
      context: ./demo-application
      dockerfile: Dockerfile
    container_name: demo-application
    ports:
      - "8888:8888"

  product-service:
    build:
      context: ./Product
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - demo-application
      - mysql-db
    restart: on-failure

  purchase-service:
    build:
      context: ./Order
      dockerfile: Dockerfile
    container_name: purchase-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - demo-application
      - mysql-db
    restart: on-failure

  clientele-service:
    build:
      context: ./Customer
      dockerfile: Dockerfile
    container_name: clientele-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - demo-application
      - mysql-db
    restart: on-failure

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
